<a href="https://colab.research.google.com/github/gyujin0450/RPRG/blob/master/p068_matrix%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# R 행렬 연산
https://rfriend.tistory.com/40

In [ ]:
## 행렬 X와 행렬 Y 생성
x <- matrix(1:4, nrow=2, ncol=2, byrow = F, dimnames = NULL)
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [ ]:
y <- matrix(5:8, nrow=2, byrow = T)
y

[,1] [,2]
[1,] 5    6   
[2,] 7    8

In [ ]:
x + y  # (1+5),(3+6),(2+7),(4+8)

[,1] [,2]
[1,] 6     9  
[2,] 9    12

In [ ]:
x - y # (1-5),(3-6),(2-7),(4-8)

[,1] [,2]
[1,] -4   -3  
[2,] -5   -4

In [ ]:
x * y # 선형대수의 행렬 곱이 아니라 각 구성 원소의 순소대로 그냥 곱하는 것 cf) 선형대수곱은 x%*%Y 로 함

[,1] [,2]
[1,]  5   18  
[2,] 14   32

In [ ]:
x %*% y # (1*5 + 3*7),(1*6 + 3*8),(2*5 + 4*7),(2*6 + 4*8)

[,1] [,2]
[1,] 26   30  
[2,] 38   44

In [ ]:
# cf) p68 예제 : matrix와 vector의 연산임!!
z <- matrix(c(1:9), nrow=3)
a <- c(1,2,3)
z
a

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] 1 2 3

In [ ]:
z + a # (1,4,7)+1 , (2,5,8)+2, (3,6,9)+3

[,1] [,2] [,3]
[1,] 2    5     8  
[2,] 4    7    10  
[3,] 6    9    12

In [ ]:
z - a # (1,4,7)-1 , (2,5,8)-2, (3,6,9)-3

[,1] [,2] [,3]
[1,] 0    3    6   
[2,] 0    3    6   
[3,] 0    3    6

In [ ]:
z * a # (1,4,7)*1 , (2,5,6)*2, (3,6,9)*3 

[,1] [,2] [,3]
[1,] 1     4    7  
[2,] 4    10   16  
[3,] 9    18   27