<a href="https://colab.research.google.com/github/gyujin0450/RPRG/blob/master/p069_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ch2.3 Array 자료구조

In [ ]:
# 배열 생성 : 같은 자료형을 갖는 다차원 배열 구조
v <- c(1:12)
arr <- array(v, c(3,2,2)) # "3행 2열 2면" 의 3차원 배열 생성
arr # RStudio에서 결과 확인 필요!!

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

In [ ]:
arr[,,1]

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [ ]:
arr[,,2]

[,1] [,2]
[1,] 7    10  
[2,] 8    11  
[3,] 9    12

In [ ]:
mode(arr);class(arr)

[1] "numeric"

[1] "array"

In [ ]:
# 데이터 셋 가져오기
install.packages("RSADBE")
# installed.packages()
library(RSADBE)
# search()
data("Bug_Metrics_Software")
Bug_Metrics_Software # 소프트웨어별 발표전후 버그측정 결과를 3차원 배열 구조로 제공함

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



, , BA_Ind = Before

         Bugs
Software   Bugs NT.Bugs Major Critical H.Priority
  JDT     11605   10119  1135      432        459
  PDE      5803    4191   362      100         96
  Equinox   325    1393   156       71         14
  Lucene   1714    1714     0        0          0
  Mylyn   14577    6806   592      235       8804

, , BA_Ind = After

         Bugs
Software   Bugs NT.Bugs Major Critical H.Priority
  JDT       374      17    35       10          3
  PDE       341      14    57        6          0
  Equinox   244       3     4        1          0
  Lucene     97       0     0        0          0
  Mylyn     340     187    18        3         36
