<a href="https://colab.research.google.com/github/gyujin0450/RPRG/blob/master/p63_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ch2.2 Matrix 자료 구조

In [ ]:
# 벡터를 이용한 행렬 객체 생성
m <- matrix(c(1:5))
m

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5

In [ ]:
# 백터의 열우선(colume) 행렬 객체 생성
m <- matrix(c(1:100), nrow=10)
m

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  1   11   21   31   41   51   61   71   81    91  
 [2,]  2   12   22   32   42   52   62   72   82    92  
 [3,]  3   13   23   33   43   53   63   73   83    93  
 [4,]  4   14   24   34   44   54   64   74   84    94  
 [5,]  5   15   25   35   45   55   65   75   85    95  
 [6,]  6   16   26   36   46   56   66   76   86    96  
 [7,]  7   17   27   37   47   57   67   77   87    97  
 [8,]  8   18   28   38   48   58   68   78   88    98  
 [9,]  9   19   29   39   49   59   69   79   89    99  
[10,] 10   20   30   40   50   60   70   80   90   100

In [ ]:
# 백터의 행우선(row) 행렬 객체 생성
m <- matrix(c(1:100), nrow = 10, byrow = T)
m

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  1    2    3    4    5    6    7    8    9    10  
 [2,] 11   12   13   14   15   16   17   18   19    20  
 [3,] 21   22   23   24   25   26   27   28   29    30  
 [4,] 31   32   33   34   35   36   37   38   39    40  
 [5,] 41   42   43   44   45   46   47   48   49    50  
 [6,] 51   52   53   54   55   56   57   58   59    60  
 [7,] 61   62   63   64   65   66   67   68   69    70  
 [8,] 71   72   73   74   75   76   77   78   79    80  
 [9,] 81   82   83   84   85   86   87   88   89    90  
[10,] 91   92   93   94   95   96   97   98   99   100

In [ ]:
# 행 묶음으로 행렬 객체 생성하기
x1 <- c(1:10) 
x2 <- c(11:20)
m <- rbind(x1,x2)
m

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
x1  1    2    3    4    5    6    7    8    9   10   
x2 11   12   13   14   15   16   17   18   19   20

In [ ]:
# 열 묶음으로 행렬 객체 생성하기
m <- cbind(x1,x2)
m 

x1 x2
 [1,]  1 11
 [2,]  2 12
 [3,]  3 13
 [4,]  4 14
 [5,]  5 15
 [6,]  6 16
 [7,]  7 17
 [8,]  8 18
 [9,]  9 19
[10,] 10 20

In [ ]:
# 2행으로 행렬 객체 생성하기
# m1 <- matrix(10:20,2) # 오류 발생
m2 <- matrix(10:19,2)
m2
mode(m2)
class(m2)

[,1] [,2] [,3] [,4] [,5]
[1,] 10   12   14   16   18  
[2,] 11   13   15   17   19

[1] "numeric"

[1] "matrix"

In [ ]:
# 첨자를 사용하여 행렬 객체에 접근하기
m2[1,] # 1행 전체 원소 출력

[1] 10 12 14 16 18

In [ ]:
m2[,5] # 5열 전체 원소 출력

[1] 18 19

In [ ]:
m2[2,3]

[1] 15

In [ ]:
m3[1,c(2:5)]

[1] 12 14 16 18

In [2]:
# 3*3의 행렬 객체 생성하기
m3 <- matrix(c(1:9), nrow=3, ncol=3)
m3
m4 <- matrix(c(1:9), nrow=3, byrow = T)
m4

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [ ]:
# 행렬 객체 처리 함수 - 자료의 갯수 보기
length(m4)

[1] 9

In [ ]:
nrow(m4)
ncol(m4)

[1] 3

[1] 3

In [ ]:
# apply(행렬객체, 1:행단위 | 2:열단위 , 행렬자료에 적용할 함수) 함수
apply(m4, 1, max)

[1] 3 6 9

In [ ]:
apply(m4,1, mean)

[1] 2 5 8

In [ ]:
apply(m4,2,max)

[1] 7 8 9

In [ ]:
# Test
m5 <- matrix(c(9:1), nrow=3)
m5

[,1] [,2] [,3]
[1,] 9    6    3   
[2,] 8    5    2   
[3,] 7    4    1

In [ ]:
apply(m5,2,max) # m5에서 열단위로 최대값 출력!!

[1] 9 6 3

In [ ]:
# 사용자 정의 함수
f <- function(x) {
  x * c(1,2,3) # Q) 행렬 연산 ???
} 

m3
r <- apply(m3, 1, f) # 행단위으로 함수 f 적용(??)
r                    # 벡터 데이터 연산할 때 열단위로 결과 출력(https://www.youtube.com/watch?v=JpSe38UHaos) 


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  8   10   12  
[3,] 21   24   27

In [3]:
# 행렬 객체에 컬럼명 지정하기
colnames(m3) <- c("c1","c2","c3")
rownames(m3) <- c("r1","r2","r3")
m3

c1 c2 c3
r1 1  4  7 
r2 2  5  8 
r3 3  6  9